package com.firestream.chat.ui.chat

/**
 * Bundled emoji keyword lookup table for in-panel search (no network required).
 * Keys are emoji characters; values are keyword lists used for prefix-match search.
 */
internal object EmojiSearchData {

    private val table: Map<String, List<String>> = mapOf(
        // Smileys & Emotion
        "😀" to listOf("grinning", "smile", "happy", "face"),
        "😃" to listOf("grinning", "big eyes", "happy", "smile"),
        "😄" to listOf("grinning", "smile", "happy", "laugh"),
        "😁" to listOf("beaming", "grin", "smile", "happy"),
        "😆" to listOf("grinning squinting", "laugh", "lol", "haha"),
        "😅" to listOf("sweat smile", "nervous laugh", "relief"),
        "🤣" to listOf("rolling floor laughing", "rofl", "lol", "funny"),
        "😂" to listOf("tears joy", "laughing", "cry laugh", "lol"),
        "🙂" to listOf("slightly smiling", "smile", "nice"),
        "🙃" to listOf("upside down", "silly", "sarcasm"),
        "😉" to listOf("winking", "wink", "flirt"),
        "😊" to listOf("smiling eyes", "blush", "happy", "cute"),
        "😇" to listOf("halo", "angel", "innocent"),
        "🥰" to listOf("smiling hearts", "love", "adore", "in love"),
        "😍" to listOf("heart eyes", "love", "adore", "beautiful"),
        "🤩" to listOf("star struck", "amazed", "excited", "wow"),
        "😘" to listOf("kiss", "blowing kiss", "love"),
        "😗" to listOf("kissing", "kiss"),
        "😙" to listOf("kissing smiling eyes", "kiss", "cute"),
        "😚" to listOf("kissing closed eyes", "kiss", "love"),
        "😋" to listOf("yum", "delicious", "tasty", "tongue"),
        "😛" to listOf("tongue", "silly", "playful"),
        "😜" to listOf("winking tongue", "silly", "joking", "playful"),
        "🤪" to listOf("zany", "crazy", "wild", "goofy"),
        "😝" to listOf("squinting tongue", "gross", "silly"),
        "🤑" to listOf("money mouth", "rich", "greedy", "dollar"),
        "🤗" to listOf("hugging", "hug", "warm"),
        "🤭" to listOf("hand over mouth", "oops", "giggle", "secret"),
        "🤫" to listOf("shushing", "quiet", "secret", "shhh"),
        "🤔" to listOf("thinking", "hmm", "pondering", "wonder"),
        "🤐" to listOf("zipper mouth", "silent", "secret", "zip"),
        "🤨" to listOf("raised eyebrow", "skeptical", "suspicious"),
        "😐" to listOf("neutral face", "expressionless", "blank"),
        "😑" to listOf("expressionless", "blank", "no expression"),
        "😶" to listOf("no mouth", "silent", "speechless"),
        "😏" to listOf("smirking", "smirk", "sly", "flirt"),
        "😒" to listOf("unamused", "unimpressed", "meh"),
        "🙄" to listOf("eye roll", "whatever", "bored", "annoyed"),
        "😬" to listOf("grimacing", "awkward", "nervous"),
        "🤥" to listOf("lying face", "pinocchio", "liar"),
        "😌" to listOf("relieved", "peaceful", "calm", "content"),
        "😔" to listOf("pensive", "sad", "thoughtful"),
        "😪" to listOf("sleepy", "tired", "sleep"),
        "🤤" to listOf("drooling", "hungry", "yummy"),
        "😴" to listOf("sleeping", "zzz", "sleep", "tired", "night"),
        "😷" to listOf("mask", "sick", "medical", "illness"),
        "🤒" to listOf("thermometer face", "sick", "fever", "ill"),
        "🤕" to listOf("bandage", "hurt", "injured", "sick"),
        "🤢" to listOf("nauseated", "sick", "gross", "disgusting"),
        "🤮" to listOf("vomiting", "sick", "gross", "puke"),
        "🤧" to listOf("sneezing", "sick", "cold", "tissue"),
        "🥵" to listOf("hot face", "hot", "sweating", "fever"),
        "🥶" to listOf("cold face", "cold", "freezing", "blue"),
        "🥴" to listOf("woozy", "dizzy", "drunk", "tipsy"),
        "😵" to listOf("dizzy face", "stunned", "knocked out"),
        "🤯" to listOf("exploding head", "mind blown", "shocked", "wow"),
        "🤠" to listOf("cowboy", "hat", "western", "yeehaw"),
        "🥸" to listOf("disguised face", "glasses", "incognito", "spy"),
        "😎" to listOf("sunglasses", "cool", "awesome", "confident"),
        "🤓" to listOf("nerd", "glasses", "geek", "study"),
        "🧐" to listOf("monocle", "curious", "detective", "fancy"),
        "😕" to listOf("confused", "uncertain", "puzzled"),
        "😟" to listOf("worried", "concern", "anxious"),
        "🙁" to listOf("slightly frowning", "sad", "unhappy"),
        "☹️" to listOf("frowning", "sad", "unhappy", "upset"),
        "😮" to listOf("open mouth", "surprised", "gasp", "wow"),
        "😯" to listOf("hushed", "surprised", "shocked", "quiet"),
        "😲" to listOf("astonished", "shocked", "amazed", "wow"),
        "😳" to listOf("flushed", "embarrassed", "shocked", "blush"),
        "🥺" to listOf("pleading eyes", "puppy eyes", "cute", "beg"),
        "😦" to listOf("frowning open mouth", "sad", "shocked"),
        "😧" to listOf("anguished", "distress", "pain"),
        "😨" to listOf("fearful", "scared", "fear", "worried"),
        "😰" to listOf("anxious sweat", "nervous", "worried", "stress"),
        "😥" to listOf("sad relieved", "disappointed", "worried"),
        "😢" to listOf("crying", "sad", "tear", "cry"),
        "😭" to listOf("loudly crying", "sob", "bawling", "sad"),
        "😱" to listOf("screaming fear", "shocked", "scared", "horror"),
        "😖" to listOf("confounded", "frustrated", "stressed"),
        "😣" to listOf("persevering", "struggling", "stressed"),
        "😞" to listOf("disappointed", "sad", "letdown"),
        "😓" to listOf("downcast sweat", "nervous", "disappointed"),
        "😩" to listOf("weary", "tired", "exhausted", "ugh"),
        "😫" to listOf("tired face", "exhausted", "worn out"),
        "🥱" to listOf("yawning", "bored", "tired", "sleepy"),
        "😤" to listOf("triumph", "huffing", "angry", "proud"),
        "😡" to listOf("pouting", "angry", "mad", "red"),
        "😠" to listOf("angry", "mad", "irritated", "cross"),
        "🤬" to listOf("cursing", "swearing", "angry", "rage"),
        "😈" to listOf("devil", "evil smile", "mischievous", "horns"),
        "👿" to listOf("angry devil", "evil", "demon", "imp"),
        "💀" to listOf("skull", "dead", "death", "skeleton"),
        "☠️" to listOf("skull crossbones", "dead", "danger", "poison"),
        "💩" to listOf("poop", "poo", "pile of poo", "funny"),
        "🤡" to listOf("clown", "joker", "funny", "circus"),
        "👹" to listOf("ogre", "monster", "evil", "red"),
        "👺" to listOf("goblin", "monster", "green", "evil"),
        "👻" to listOf("ghost", "halloween", "spooky", "boo"),
        "👽" to listOf("alien", "extraterrestrial", "space", "ufo"),
        "👾" to listOf("alien monster", "space invader", "game", "pixel"),
        "🤖" to listOf("robot", "bot", "android", "machine"),
        "😺" to listOf("grinning cat", "cat", "smile"),
        "😸" to listOf("grinning cat eyes", "cat", "happy"),
        "😹" to listOf("cat tears joy", "cat", "laughing"),
        "😻" to listOf("heart eyes cat", "cat", "love"),
        "😼" to listOf("cat smirk", "cat", "sly"),
        "😽" to listOf("kissing cat", "cat", "kiss"),
        "🙀" to listOf("weary cat", "cat", "shocked", "scared"),
        "😿" to listOf("crying cat", "cat", "sad"),
        "😾" to listOf("pouting cat", "cat", "angry"),

        // People & Body
        "👋" to listOf("wave", "waving", "hello", "bye"),
        "🤚" to listOf("raised back hand", "hand", "stop"),
        "🖐️" to listOf("hand splayed", "hand", "five"),
        "✋" to listOf("raised hand", "stop", "high five"),
        "🖖" to listOf("vulcan salute", "star trek", "spock", "live long"),
        "👌" to listOf("ok hand", "perfect", "okay", "good"),
        "🤌" to listOf("pinched fingers", "chef kiss", "perfect", "italian"),
        "🤏" to listOf("pinching hand", "small", "little"),
        "✌️" to listOf("victory", "peace", "two", "v sign"),
        "🤞" to listOf("crossed fingers", "luck", "hope", "wish"),
        "🤟" to listOf("love you gesture", "ily", "love", "rock"),
        "🤘" to listOf("sign of horns", "rock", "metal", "cool"),
        "🤙" to listOf("call me", "shaka", "hang loose", "phone"),
        "👈" to listOf("pointing left", "left", "direction"),
        "👉" to listOf("pointing right", "right", "direction"),
        "👆" to listOf("pointing up", "up", "above"),
        "🖕" to listOf("middle finger", "offensive", "rude"),
        "👇" to listOf("pointing down", "down", "below"),
        "☝️" to listOf("index pointing up", "one", "important"),
        "👍" to listOf("thumbs up", "like", "approve", "good", "yes"),
        "👎" to listOf("thumbs down", "dislike", "no", "bad"),
        "✊" to listOf("raised fist", "punch", "power", "solidarity"),
        "👊" to listOf("oncoming fist", "punch", "fist bump"),
        "🤛" to listOf("left facing fist", "fist bump"),
        "🤜" to listOf("right facing fist", "fist bump"),
        "👏" to listOf("clapping hands", "applause", "clap", "bravo"),
        "🙌" to listOf("raising hands", "praise", "hooray", "celebration"),
        "👐" to listOf("open hands", "hug", "welcome"),
        "🤲" to listOf("palms up", "prayer", "ask", "begging"),
        "🤝" to listOf("handshake", "deal", "agreement", "partnership"),
        "🙏" to listOf("folded hands", "pray", "please", "thank you", "namaste"),
        "✍️" to listOf("writing hand", "write", "note", "sign"),
        "💅" to listOf("nail polish", "nails", "manicure", "fancy"),
        "🤳" to listOf("selfie", "camera", "phone", "photo"),
        "💪" to listOf("flexed bicep", "strong", "muscle", "gym", "workout"),
        "🦾" to listOf("mechanical arm", "prosthetic", "strong", "robot"),
        "🦵" to listOf("leg", "kick", "muscle"),
        "🦶" to listOf("foot", "kick", "stomp"),
        "👂" to listOf("ear", "listen", "hearing"),
        "🦻" to listOf("ear hearing aid", "deaf", "hearing"),
        "👃" to listOf("nose", "smell", "sniff"),
        "🫀" to listOf("anatomical heart", "heart", "organ", "health"),
        "🫁" to listOf("lungs", "breathe", "organ", "health"),
        "🧠" to listOf("brain", "smart", "think", "intelligence"),
        "🦷" to listOf("tooth", "teeth", "dentist"),
        "🦴" to listOf("bone", "skeleton", "strong"),
        "👀" to listOf("eyes", "look", "watching", "see", "stare"),
        "👁️" to listOf("eye", "see", "look", "vision"),
        "👅" to listOf("tongue", "taste", "mouth"),
        "👄" to listOf("mouth", "lips", "kiss", "beauty"),
        "🫦" to listOf("biting lip", "nervous", "flirty", "attractive"),
        "👶" to listOf("baby", "infant", "child", "cute"),
        "🧒" to listOf("child", "kid", "young"),
        "👦" to listOf("boy", "man", "male", "kid"),
        "👧" to listOf("girl", "female", "kid"),
        "🧑" to listOf("person", "human", "adult"),
        "👱" to listOf("blond person", "blonde", "fair"),
        "👨" to listOf("man", "male", "adult"),
        "👩" to listOf("woman", "female", "adult"),
        "🧓" to listOf("older person", "elderly", "senior"),
        "👴" to listOf("old man", "grandfather", "elderly"),
        "👵" to listOf("old woman", "grandmother", "elderly"),
        "🙍" to listOf("person frowning", "unhappy", "sad"),
        "🙎" to listOf("person pouting", "angry", "sulk"),
        "🙅" to listOf("person gesturing no", "no", "stop", "deny"),
        "🙆" to listOf("person gesturing ok", "ok", "okay", "good"),
        "💁" to listOf("information desk", "sassy", "hand flip"),
        "🙋" to listOf("person raising hand", "question", "me", "hi"),
        "🧏" to listOf("deaf person", "sign language", "hearing"),
        "🙇" to listOf("person bowing", "bow", "thanks", "sorry"),
        "🤦" to listOf("facepalm", "frustrated", "duh", "smh"),
        "🤷" to listOf("shrug", "whatever", "idk", "dunno"),
        "🧑‍⚕️" to listOf("health worker", "doctor", "nurse", "medical"),
        "🧑‍🏫" to listOf("teacher", "education", "school"),
        "🧑‍🍳" to listOf("cook", "chef", "food", "kitchen"),
        "🧑‍🔧" to listOf("mechanic", "fix", "repair", "tools"),
        "🧑‍💻" to listOf("technologist", "programmer", "computer", "coding"),
        "🧑‍🎤" to listOf("singer", "music", "performer", "star"),
        "🧑‍🎨" to listOf("artist", "paint", "creative", "art"),
        "🧑‍🚒" to listOf("firefighter", "fire", "rescue"),
        "🧑‍✈️" to listOf("pilot", "airplane", "fly", "aviation"),
        "🧑‍🚀" to listOf("astronaut", "space", "rocket"),
        "🧑‍⚖️" to listOf("judge", "law", "justice", "court"),
        "💂" to listOf("guard", "soldier", "security"),
        "🕵️" to listOf("detective", "spy", "investigation"),
        "👷" to listOf("construction worker", "hard hat", "build"),
        "🤴" to listOf("prince", "royalty", "crown"),
        "👸" to listOf("princess", "queen", "royalty", "crown"),
        "👳" to listOf("person wearing turban", "turban", "religion"),
        "👲" to listOf("person skullcap", "hat", "asian"),
        "🧕" to listOf("woman headscarf", "hijab", "modesty"),
        "🤵" to listOf("person tuxedo", "suit", "wedding", "formal"),
        "👰" to listOf("person veil", "bride", "wedding", "marriage"),
        "🤰" to listOf("pregnant woman", "pregnancy", "baby", "expecting"),
        "🤱" to listOf("breast feeding", "baby", "nursing"),
        "🧙" to listOf("mage", "wizard", "witch", "magic"),
        "🧚" to listOf("fairy", "magic", "wings", "fantasy"),
        "🧛" to listOf("vampire", "dracula", "blood", "halloween"),
        "🧜" to listOf("merperson", "mermaid", "sea", "ocean"),
        "🧝" to listOf("elf", "fantasy", "lord of rings", "magic"),
        "🧞" to listOf("genie", "wish", "lamp", "magic"),
        "🧟" to listOf("zombie", "undead", "horror", "halloween"),
        "💆" to listOf("person massage", "relax", "spa", "massage"),
        "💇" to listOf("person haircut", "hair", "barber", "salon"),
        "🚶" to listOf("walking", "walk", "stroll"),
        "🧍" to listOf("standing person", "stand"),
        "🧎" to listOf("kneeling", "kneel", "pray"),
        "🏃" to listOf("running", "run", "sprint", "exercise", "fast"),
        "💃" to listOf("dancing woman", "dance", "salsa", "party"),
        "🕺" to listOf("dancing man", "dance", "disco", "party"),
        "🕴️" to listOf("levitate", "business", "suit"),
        "👯" to listOf("people bunny ears", "twins", "party", "dance"),
        "🧖" to listOf("person sauna", "steam", "relax", "spa"),
        "🧗" to listOf("climbing", "rock climbing", "adventure"),
        "🤺" to listOf("fencing", "sword", "sport"),
        "🏇" to listOf("horse racing", "horse", "race", "jockey"),
        "⛷️" to listOf("skiing", "ski", "snow", "winter"),
        "🏂" to listOf("snowboarding", "snow", "board", "winter"),
        "🏌️" to listOf("golf", "golfer", "sport"),
        "🏄" to listOf("surfing", "surf", "wave", "beach", "ocean"),
        "🚣" to listOf("rowing boat", "row", "water"),
        "🧘" to listOf("yoga", "meditation", "zen", "lotus"),
        "🏊" to listOf("swimming", "swim", "pool", "water"),
        "🤽" to listOf("water polo", "swimming", "sport"),
        "🚴" to listOf("cycling", "bike", "bicycle", "sport"),
        "🏋️" to listOf("weight lifting", "gym", "strong", "barbell"),
        "🤼" to listOf("wrestling", "fight", "sport"),
        "🤸" to listOf("cartwheeling", "gymnastics", "flip"),
        "🤾" to listOf("handball", "sport", "ball"),
        "🏌️" to listOf("golf", "sport"),
        "🏹" to listOf("bow arrow", "archery", "shoot"),
        "🧑‍🤝‍🧑" to listOf("people holding hands", "couple", "together", "friends"),
        "👫" to listOf("woman man holding hands", "couple", "love", "date"),
        "👬" to listOf("men holding hands", "couple", "friends"),
        "👭" to listOf("women holding hands", "couple", "friends"),
        "💏" to listOf("kiss", "kissing", "couple", "love"),
        "💑" to listOf("couple heart", "love", "romance"),
        "👪" to listOf("family", "home", "parents", "children"),

        // Animals
        "🐶" to listOf("dog face", "dog", "pet", "puppy", "woof"),
        "🐱" to listOf("cat face", "cat", "pet", "meow", "kitten"),
        "🐭" to listOf("mouse face", "mouse", "rodent"),
        "🐹" to listOf("hamster face", "hamster", "pet", "cute"),
        "🐰" to listOf("rabbit face", "rabbit", "bunny", "cute"),
        "🦊" to listOf("fox face", "fox", "sly", "clever"),
        "🐻" to listOf("bear face", "bear", "animal"),
        "🐼" to listOf("panda face", "panda", "bear", "cute"),
        "🐨" to listOf("koala", "bear", "australia", "cute"),
        "🐯" to listOf("tiger face", "tiger", "cat", "stripes"),
        "🦁" to listOf("lion face", "lion", "king", "roar"),
        "🐮" to listOf("cow face", "cow", "moo", "farm"),
        "🐷" to listOf("pig face", "pig", "oink", "farm"),
        "🐸" to listOf("frog face", "frog", "green", "pond"),
        "🐵" to listOf("monkey face", "monkey", "animal"),
        "🙈" to listOf("see no evil monkey", "hide", "shy", "monkey"),
        "🙉" to listOf("hear no evil monkey", "deaf", "monkey"),
        "🙊" to listOf("speak no evil monkey", "silent", "monkey"),
        "🐔" to listOf("chicken", "bird", "farm", "cluck"),
        "🐧" to listOf("penguin", "bird", "arctic", "cute"),
        "🐦" to listOf("bird", "tweet", "fly"),
        "🦆" to listOf("duck", "quack", "water", "bird"),
        "🦅" to listOf("eagle", "bird", "freedom", "fly"),
        "🦉" to listOf("owl", "wise", "night", "bird"),
        "🦇" to listOf("bat", "night", "vampire", "halloween"),
        "🐺" to listOf("wolf face", "wolf", "howl", "animal"),
        "🐗" to listOf("boar", "pig", "wild", "animal"),
        "🐴" to listOf("horse face", "horse", "ride"),
        "🦄" to listOf("unicorn", "magic", "rainbow", "fantasy"),
        "🐝" to listOf("honeybee", "bee", "honey", "sting"),
        "🐛" to listOf("bug", "caterpillar", "insect"),
        "🦋" to listOf("butterfly", "insect", "beautiful", "wings"),
        "🐌" to listOf("snail", "slow", "shell"),
        "🐞" to listOf("ladybug", "bug", "insect", "red"),
        "🐜" to listOf("ant", "insect", "tiny", "colony"),
        "🦟" to listOf("mosquito", "bug", "bite", "insect"),
        "🦗" to listOf("cricket", "insect", "chirp"),
        "🕷️" to listOf("spider", "web", "creepy", "halloween"),
        "🦂" to listOf("scorpion", "sting", "zodiac", "dangerous"),
        "🐢" to listOf("turtle", "slow", "shell", "reptile"),
        "🐍" to listOf("snake", "reptile", "slither", "danger"),
        "🦎" to listOf("lizard", "reptile", "gecko"),
        "🦖" to listOf("t rex", "dinosaur", "extinct", "jurassic"),
        "🦕" to listOf("sauropod", "dinosaur", "long neck", "extinct"),
        "🐙" to listOf("octopus", "tentacles", "sea", "ocean"),
        "🦑" to listOf("squid", "tentacles", "sea", "ink"),
        "🦞" to listOf("lobster", "seafood", "red", "ocean"),
        "🦀" to listOf("crab", "seafood", "claws", "ocean"),
        "🐡" to listOf("blowfish", "fish", "spiky", "ocean"),
        "🐠" to listOf("tropical fish", "fish", "colorful", "ocean"),
        "🐟" to listOf("fish", "sea", "ocean", "swim"),
        "🐬" to listOf("dolphin", "ocean", "smart", "swim"),
        "🐳" to listOf("whale spouting", "whale", "ocean", "big"),
        "🦈" to listOf("shark", "ocean", "dangerous", "swim"),
        "🐊" to listOf("crocodile", "alligator", "reptile", "dangerous"),
        "🐅" to listOf("tiger", "stripes", "wild", "cat"),
        "🐆" to listOf("leopard", "spots", "wild", "cat"),
        "🦓" to listOf("zebra", "stripes", "africa"),
        "🦍" to listOf("gorilla", "ape", "strong", "animal"),
        "🐘" to listOf("elephant", "big", "trunk", "africa"),
        "🦏" to listOf("rhinoceros", "horn", "africa"),
        "🦛" to listOf("hippopotamus", "hippo", "africa", "water"),
        "🐪" to listOf("camel", "desert", "hump", "dry"),
        "🦒" to listOf("giraffe", "tall", "neck", "africa"),
        "🦘" to listOf("kangaroo", "australia", "jump", "pouch"),
        "🐃" to listOf("water buffalo", "cow", "farm"),
        "🐂" to listOf("ox", "bull", "farm"),
        "🐄" to listOf("cow", "farm", "milk", "moo"),
        "🐎" to listOf("horse", "gallop", "race", "fast"),
        "🐖" to listOf("pig", "farm", "pork"),
        "🐏" to listOf("ram", "sheep", "lamb", "farm"),
        "🐑" to listOf("ewe", "sheep", "wool", "cute"),
        "🐐" to listOf("goat", "farm", "billy"),
        "🦌" to listOf("deer", "antlers", "forest", "bambi"),
        "🐕" to listOf("dog", "pet", "canine"),
        "🐈" to listOf("cat", "pet", "feline"),
        "🐓" to listOf("rooster", "chicken", "farm", "morning"),
        "🦃" to listOf("turkey", "thanksgiving", "bird"),
        "🦤" to listOf("dodo", "extinct", "bird"),
        "🦩" to listOf("flamingo", "pink", "bird", "elegant"),
        "🦚" to listOf("peacock", "feathers", "colorful", "bird"),
        "🦜" to listOf("parrot", "colorful", "talk", "bird"),
        "🦢" to listOf("swan", "graceful", "white", "bird"),
        "🦭" to listOf("seal", "ocean", "cute", "clap"),
        "🐿️" to listOf("chipmunk", "squirrel", "nut", "cute"),
        "🦔" to listOf("hedgehog", "spiky", "cute", "animal"),

        // Food & Drink
        "🍎" to listOf("red apple", "apple", "fruit", "food"),
        "🍐" to listOf("pear", "fruit", "food", "green"),
        "🍊" to listOf("tangerine", "orange", "fruit", "citrus"),
        "🍋" to listOf("lemon", "citrus", "sour", "yellow", "fruit"),
        "🍌" to listOf("banana", "fruit", "yellow", "tropical"),
        "🍉" to listOf("watermelon", "fruit", "summer", "red"),
        "🍇" to listOf("grapes", "fruit", "purple", "wine"),
        "🍓" to listOf("strawberry", "fruit", "red", "sweet"),
        "🫐" to listOf("blueberry", "fruit", "blue", "berry"),
        "🍈" to listOf("melon", "fruit", "green"),
        "🍒" to listOf("cherries", "fruit", "red", "sweet"),
        "🍑" to listOf("peach", "fruit", "fuzzy", "pink"),
        "🥭" to listOf("mango", "tropical", "fruit", "orange"),
        "🍍" to listOf("pineapple", "tropical", "fruit", "spiky"),
        "🥥" to listOf("coconut", "tropical", "fruit", "white"),
        "🥝" to listOf("kiwi fruit", "kiwi", "green", "fruit"),
        "🍅" to listOf("tomato", "red", "vegetable", "pizza"),
        "🫒" to listOf("olive", "green", "oil", "mediterranean"),
        "🥑" to listOf("avocado", "green", "healthy", "toast"),
        "🍆" to listOf("eggplant", "purple", "vegetable"),
        "🥔" to listOf("potato", "vegetable", "starchy"),
        "🥕" to listOf("carrot", "orange", "vegetable", "healthy"),
        "🌽" to listOf("corn", "yellow", "vegetable", "summer"),
        "🌶️" to listOf("hot pepper", "spicy", "chili", "red", "hot"),
        "🫑" to listOf("bell pepper", "pepper", "vegetable"),
        "🥒" to listOf("cucumber", "green", "vegetable", "cool"),
        "🥬" to listOf("leafy greens", "lettuce", "vegetable", "salad"),
        "🥦" to listOf("broccoli", "green", "vegetable", "healthy"),
        "🧄" to listOf("garlic", "cooking", "smell", "flavor"),
        "🧅" to listOf("onion", "cooking", "cry", "tears"),
        "🍄" to listOf("mushroom", "fungi", "mario", "red"),
        "🥜" to listOf("peanuts", "nuts", "snack"),
        "🌰" to listOf("chestnut", "nut", "autumn", "fall"),
        "🍞" to listOf("bread", "loaf", "bake", "food"),
        "🥐" to listOf("croissant", "french", "breakfast", "pastry"),
        "🥖" to listOf("baguette", "french", "bread"),
        "🫓" to listOf("flatbread", "pita", "bread"),
        "🥨" to listOf("pretzel", "salty", "snack"),
        "🥯" to listOf("bagel", "bread", "breakfast"),
        "🧀" to listOf("cheese", "dairy", "yellow", "melted"),
        "🥚" to listOf("egg", "breakfast", "food", "protein"),
        "🍳" to listOf("cooking", "frying pan", "egg", "breakfast"),
        "🧈" to listOf("butter", "dairy", "spread"),
        "🥞" to listOf("pancakes", "stack", "breakfast", "maple"),
        "🧇" to listOf("waffle", "breakfast", "crispy", "syrup"),
        "🥓" to listOf("bacon", "pork", "breakfast", "crispy"),
        "🥩" to listOf("cut of meat", "steak", "beef", "food"),
        "🍗" to listOf("poultry leg", "chicken", "drumstick", "food"),
        "🍖" to listOf("meat on bone", "ribs", "barbecue", "food"),
        "🦴" to listOf("bone", "dog", "skeleton"),
        "🌭" to listOf("hot dog", "sausage", "american", "food"),
        "🍔" to listOf("hamburger", "burger", "fast food", "beef"),
        "🍟" to listOf("french fries", "fries", "fast food", "chips"),
        "🍕" to listOf("pizza", "cheese", "italian", "food"),
        "🫔" to listOf("tamale", "wrap", "mexican", "food"),
        "🌮" to listOf("taco", "mexican", "food", "shell"),
        "🌯" to listOf("burrito", "wrap", "mexican", "food"),
        "🥙" to listOf("stuffed flatbread", "pita", "wrap"),
        "🧆" to listOf("falafel", "middle east", "vegetarian", "food"),
        "🥚" to listOf("egg", "food", "breakfast"),
        "🍿" to listOf("popcorn", "movie", "snack", "cinema"),
        "🧂" to listOf("salt", "seasoning", "shaker"),
        "🥫" to listOf("canned food", "tin", "can"),
        "🍱" to listOf("bento box", "japanese", "lunch", "box"),
        "🍣" to listOf("sushi", "japanese", "fish", "rice"),
        "🍜" to listOf("steaming bowl", "ramen", "noodles", "soup"),
        "🍝" to listOf("spaghetti", "pasta", "italian", "noodles"),
        "🍛" to listOf("curry rice", "curry", "indian", "spicy"),
        "🍚" to listOf("cooked rice", "rice", "japanese", "asian"),
        "🍙" to listOf("rice ball", "onigiri", "japanese"),
        "🧁" to listOf("cupcake", "cake", "sweet", "dessert", "birthday"),
        "🎂" to listOf("birthday cake", "cake", "celebration", "candles"),
        "🍰" to listOf("shortcake", "cake", "dessert", "sweet"),
        "🍩" to listOf("doughnut", "donut", "sweet", "pastry"),
        "🍪" to listOf("cookie", "biscuit", "sweet", "chocolate"),
        "🍫" to listOf("chocolate bar", "chocolate", "sweet", "candy"),
        "🍬" to listOf("candy", "sweet", "lolly"),
        "🍭" to listOf("lollipop", "candy", "sweet", "spiral"),
        "🍮" to listOf("custard", "dessert", "sweet", "pudding"),
        "🍯" to listOf("honey pot", "honey", "sweet", "bee"),
        "☕" to listOf("hot beverage", "coffee", "tea", "morning"),
        "🍵" to listOf("teacup", "tea", "green tea", "hot"),
        "🧃" to listOf("juice box", "juice", "drink"),
        "🥤" to listOf("cup straw", "soda", "drink", "cold"),
        "🧋" to listOf("bubble tea", "boba", "milk tea", "drink"),
        "🍶" to listOf("sake", "japanese", "rice wine", "drink"),
        "🍾" to listOf("champagne", "celebrate", "pop", "party"),
        "🍷" to listOf("wine glass", "wine", "red", "drink"),
        "🍸" to listOf("cocktail glass", "martini", "drink", "bar"),
        "🍹" to listOf("tropical drink", "cocktail", "summer", "juice"),
        "🍺" to listOf("beer mug", "beer", "drink", "pub", "cheers"),
        "🍻" to listOf("clinking beer mugs", "cheers", "toast", "celebrate"),
        "🥂" to listOf("clinking glasses", "champagne", "cheers", "celebrate"),
        "🥃" to listOf("tumbler glass", "whiskey", "drink", "bar"),
        "🧊" to listOf("ice", "cold", "frozen", "cube"),

        // Activities & Sports
        "⚽" to listOf("soccer ball", "football", "soccer", "sport"),
        "🏀" to listOf("basketball", "sport", "ball", "nba"),
        "🏈" to listOf("american football", "nfl", "sport", "ball"),
        "⚾" to listOf("baseball", "sport", "ball", "mlb"),
        "🥎" to listOf("softball", "sport", "ball"),
        "🎾" to listOf("tennis", "sport", "ball", "racket"),
        "🏐" to listOf("volleyball", "sport", "ball"),
        "🏉" to listOf("rugby ball", "rugby", "sport"),
        "🥏" to listOf("flying disc", "frisbee", "sport"),
        "🎱" to listOf("pool 8 ball", "billiards", "game", "8 ball"),
        "🪃" to listOf("boomerang", "australia", "throw", "sport"),
        "🏓" to listOf("ping pong", "table tennis", "sport"),
        "🏸" to listOf("badminton", "sport", "birdie", "racket"),
        "🥊" to listOf("boxing glove", "boxing", "fight", "sport"),
        "🥋" to listOf("martial arts uniform", "karate", "judo", "sport"),
        "🎿" to listOf("skis", "skiing", "snow", "winter", "sport"),
        "⛷️" to listOf("skier", "skiing", "snow", "winter"),
        "🛷" to listOf("sled", "sledding", "snow", "winter"),
        "🛹" to listOf("skateboard", "skate", "trick", "sport"),
        "🛼" to listOf("roller skate", "skating", "retro", "sport"),
        "🎯" to listOf("direct hit", "target", "bullseye", "aim", "dart"),
        "🎲" to listOf("game die", "dice", "game", "random", "luck"),
        "🎮" to listOf("video game", "gaming", "controller", "play"),
        "🕹️" to listOf("joystick", "gaming", "arcade", "retro"),
        "🎳" to listOf("bowling", "strike", "sport", "pins"),
        "🎰" to listOf("slot machine", "casino", "gambling", "luck"),
        "🧩" to listOf("puzzle piece", "puzzle", "jigsaw", "game"),
        "🎪" to listOf("circus tent", "circus", "carnival", "entertainment"),
        "🎭" to listOf("performing arts", "theater", "drama", "masks"),
        "🎨" to listOf("artist palette", "paint", "art", "creative", "color"),
        "🎬" to listOf("clapper board", "movie", "film", "action", "cinema"),
        "🎤" to listOf("microphone", "sing", "singer", "karaoke", "music"),
        "🎧" to listOf("headphone", "music", "audio", "listen"),
        "🎼" to listOf("musical score", "music", "sheet music", "notes"),
        "🎵" to listOf("musical note", "music", "note", "song"),
        "🎶" to listOf("musical notes", "music", "song", "melody"),
        "🎹" to listOf("musical keyboard", "piano", "music", "keys"),
        "🥁" to listOf("drum", "music", "beat", "percussion"),
        "🪘" to listOf("long drum", "drum", "music"),
        "🎷" to listOf("saxophone", "jazz", "music", "instrument"),
        "🎺" to listOf("trumpet", "music", "jazz", "instrument"),
        "🎸" to listOf("guitar", "music", "rock", "instrument"),
        "🪗" to listOf("accordion", "music", "folk", "instrument"),
        "🎻" to listOf("violin", "music", "classical", "instrument"),
        "🎙️" to listOf("studio microphone", "podcast", "radio", "record"),
        "🎚️" to listOf("level slider", "audio", "mixer", "music"),
        "🎛️" to listOf("control knobs", "audio", "mixer", "dj"),
        "📻" to listOf("radio", "music", "broadcast", "am fm"),
        "🎞️" to listOf("film frames", "movie", "cinema", "film"),
        "📽️" to listOf("film projector", "cinema", "movie", "projector"),
        "🎥" to listOf("movie camera", "video", "film", "record"),
        "📺" to listOf("television", "tv", "watch", "screen"),
        "📷" to listOf("camera", "photo", "picture", "picture"),
        "📸" to listOf("camera flash", "photo", "picture", "selfie"),
        "📹" to listOf("video camera", "video", "record", "film"),
        "🎊" to listOf("confetti ball", "celebrate", "party", "fun"),
        "🎉" to listOf("party popper", "celebrate", "party", "confetti", "congrats"),
        "🎈" to listOf("balloon", "party", "celebrate", "birthday"),
        "🎀" to listOf("ribbon", "gift", "bow", "pink"),
        "🎁" to listOf("wrapped gift", "present", "gift", "birthday", "christmas"),
        "🎗️" to listOf("reminder ribbon", "awareness", "ribbon"),
        "🎟️" to listOf("admission tickets", "ticket", "event"),
        "🎫" to listOf("ticket", "event", "concert", "movie"),
        "🏆" to listOf("trophy", "winner", "award", "champion", "gold"),
        "🥇" to listOf("gold medal", "first place", "winner", "gold"),
        "🥈" to listOf("silver medal", "second place", "silver"),
        "🥉" to listOf("bronze medal", "third place", "bronze"),
        "🎖️" to listOf("military medal", "award", "honor"),
        "🏅" to listOf("sports medal", "award", "medal"),
        "🎗️" to listOf("ribbon", "awareness", "cause"),
        "🃏" to listOf("joker", "card", "game", "wild"),
        "🀄" to listOf("mahjong red dragon", "mahjong", "game", "chinese"),

        // Travel & Places
        "🚗" to listOf("car", "automobile", "drive", "red"),
        "🚕" to listOf("taxi", "cab", "yellow", "car"),
        "🚙" to listOf("suv", "car", "automobile"),
        "🚌" to listOf("bus", "public transport", "commute"),
        "🚎" to listOf("trolleybus", "bus", "electric"),
        "🏎️" to listOf("racing car", "race", "fast", "formula"),
        "🚓" to listOf("police car", "police", "cop"),
        "🚑" to listOf("ambulance", "emergency", "medical", "hospital"),
        "🚒" to listOf("fire engine", "fire truck", "fire", "rescue"),
        "🚐" to listOf("minibus", "van", "transport"),
        "🛻" to listOf("pickup truck", "truck", "car"),
        "🚚" to listOf("delivery truck", "delivery", "truck"),
        "🚛" to listOf("articulated lorry", "truck", "semi"),
        "🚜" to listOf("tractor", "farm", "agriculture"),
        "🏍️" to listOf("motorcycle", "bike", "moto", "ride"),
        "🛵" to listOf("motor scooter", "scooter", "moped"),
        "🛺" to listOf("auto rickshaw", "tuk tuk", "asia"),
        "🚲" to listOf("bicycle", "bike", "cycle", "eco"),
        "🛴" to listOf("kick scooter", "scooter", "ride"),
        "🛹" to listOf("skateboard", "skate", "ride"),
        "🚁" to listOf("helicopter", "fly", "rotor", "air"),
        "🛸" to listOf("flying saucer", "ufo", "alien", "space"),
        "✈️" to listOf("airplane", "flight", "travel", "fly"),
        "🛩️" to listOf("small airplane", "plane", "fly"),
        "🚀" to listOf("rocket", "space", "launch", "fast"),
        "🛶" to listOf("canoe", "boat", "paddle", "water"),
        "⛵" to listOf("sailboat", "sail", "ocean", "water"),
        "🚤" to listOf("speedboat", "boat", "fast", "water"),
        "🛥️" to listOf("motor boat", "boat", "water"),
        "⛴️" to listOf("ferry", "boat", "water", "transport"),
        "🚢" to listOf("ship", "boat", "ocean", "cruise"),
        "🛳️" to listOf("passenger ship", "cruise", "ocean"),
        "⚓" to listOf("anchor", "ship", "nautical", "stable"),
        "🗺️" to listOf("world map", "map", "navigation", "travel"),
        "🧭" to listOf("compass", "navigation", "direction", "north"),
        "🏔️" to listOf("snow capped mountain", "mountain", "snow", "nature"),
        "⛰️" to listOf("mountain", "hiking", "nature", "peak"),
        "🌋" to listOf("volcano", "eruption", "fire", "mountain", "lava"),
        "🗻" to listOf("mount fuji", "japan", "mountain", "snow"),
        "🏕️" to listOf("camping", "tent", "nature", "outdoors"),
        "🏖️" to listOf("beach", "sand", "ocean", "summer", "vacation"),
        "🏜️" to listOf("desert", "sand", "dry", "hot", "camel"),
        "🏝️" to listOf("island", "tropical", "paradise", "beach"),
        "🏟️" to listOf("stadium", "sports", "concert", "arena"),
        "🏛️" to listOf("classical building", "museum", "history", "column"),
        "🏗️" to listOf("building construction", "build", "construction", "crane"),
        "🧱" to listOf("brick", "wall", "build", "construction"),
        "🏘️" to listOf("houses", "suburb", "neighborhood", "home"),
        "🏚️" to listOf("derelict house", "abandoned", "old", "ruin"),
        "🏠" to listOf("house", "home", "building"),
        "🏡" to listOf("house garden", "home", "yard", "suburb"),
        "🏢" to listOf("office building", "office", "work", "corporate"),
        "🏣" to listOf("japanese post office", "post", "japan"),
        "🏤" to listOf("post office", "mail", "postal"),
        "🏥" to listOf("hospital", "medical", "health", "emergency"),
        "🏦" to listOf("bank", "money", "finance"),
        "🏨" to listOf("hotel", "accommodation", "stay", "travel"),
        "🏩" to listOf("love hotel", "love", "hotel", "romance"),
        "🏪" to listOf("convenience store", "shop", "store", "buy"),
        "🏫" to listOf("school", "education", "building", "study"),
        "🏬" to listOf("department store", "shopping", "mall"),
        "🏭" to listOf("factory", "industry", "manufacturing"),
        "🗼" to listOf("tokyo tower", "japan", "tower", "landmark"),
        "🗽" to listOf("statue of liberty", "new york", "usa", "freedom"),
        "⛪" to listOf("church", "religion", "christianity", "cross"),
        "🕌" to listOf("mosque", "islam", "religion", "arabic"),
        "🛕" to listOf("hindu temple", "religion", "india"),
        "🕍" to listOf("synagogue", "jewish", "religion"),
        "⛩️" to listOf("shinto shrine", "japan", "gate", "torii"),
        "🗾" to listOf("map japan", "japan"),
        "🌁" to listOf("foggy", "fog", "mist", "city"),
        "🌃" to listOf("night with stars", "night", "city", "stars"),
        "🌆" to listOf("cityscape dusk", "city", "sunset", "evening"),
        "🌇" to listOf("sunset", "city", "evening", "dusk"),
        "🌉" to listOf("bridge night", "bridge", "night", "city"),
        "🌌" to listOf("milky way", "galaxy", "stars", "night", "space"),
        "🌠" to listOf("shooting star", "star", "wish", "space"),
        "🎆" to listOf("fireworks", "celebration", "new year", "boom"),
        "🎇" to listOf("sparkler", "fireworks", "celebration", "sparkle"),
        "🗿" to listOf("moai", "easter island", "stone", "head"),

        // Objects
        "💡" to listOf("light bulb", "idea", "bright", "lamp"),
        "🔦" to listOf("flashlight", "torch", "light", "dark"),
        "🕯️" to listOf("candle", "light", "flame", "romantic"),
        "🪔" to listOf("diya lamp", "india", "light", "oil"),
        "🧯" to listOf("fire extinguisher", "fire", "safety", "emergency"),
        "💰" to listOf("money bag", "money", "rich", "gold"),
        "💵" to listOf("dollar banknote", "money", "cash", "usd"),
        "💴" to listOf("yen banknote", "money", "japan", "yen"),
        "💶" to listOf("euro banknote", "money", "europe", "euro"),
        "💷" to listOf("pound banknote", "money", "uk", "pound"),
        "💸" to listOf("money wings", "money flying", "spend", "cash"),
        "💳" to listOf("credit card", "card", "payment", "bank"),
        "🏧" to listOf("atm sign", "atm", "cash", "bank"),
        "🪙" to listOf("coin", "money", "gold", "currency"),
        "💹" to listOf("chart increasing yen", "stocks", "finance", "yen"),
        "📈" to listOf("chart increasing", "stocks", "growth", "profit"),
        "📉" to listOf("chart decreasing", "stocks", "loss", "decline"),
        "📊" to listOf("bar chart", "chart", "data", "statistics"),
        "📋" to listOf("clipboard", "document", "list", "checklist"),
        "📌" to listOf("pushpin", "pin", "note", "location"),
        "📍" to listOf("round pushpin", "location", "pin", "map"),
        "📎" to listOf("paperclip", "attach", "link", "clip"),
        "🖇️" to listOf("linked paperclips", "link", "connect"),
        "📏" to listOf("straight ruler", "measure", "ruler"),
        "📐" to listOf("triangular ruler", "measure", "angle"),
        "✂️" to listOf("scissors", "cut", "craft", "trim"),
        "🗃️" to listOf("card file box", "organize", "file", "box"),
        "🗄️" to listOf("file cabinet", "organize", "file", "archive"),
        "🗑️" to listOf("wastebasket", "trash", "delete", "garbage"),
        "🔒" to listOf("locked", "lock", "secure", "private"),
        "🔓" to listOf("unlocked", "lock open", "access"),
        "🔏" to listOf("locked pen", "lock", "private", "sign"),
        "🔐" to listOf("locked key", "secure", "password"),
        "🔑" to listOf("key", "unlock", "password", "access"),
        "🗝️" to listOf("old key", "vintage", "key", "unlock"),
        "🔨" to listOf("hammer", "tool", "build", "hit"),
        "🪓" to listOf("axe", "chop", "wood", "tool"),
        "⛏️" to listOf("pick", "mining", "tool", "mine"),
        "⚒️" to listOf("hammer pick", "tools", "work"),
        "🛠️" to listOf("hammer wrench", "tools", "repair", "fix"),
        "🗡️" to listOf("dagger", "knife", "weapon", "sharp"),
        "⚔️" to listOf("crossed swords", "sword", "battle", "fight"),
        "🔫" to listOf("pistol", "gun", "weapon", "water gun"),
        "🏹" to listOf("bow arrow", "archery", "shoot", "aim"),
        "🛡️" to listOf("shield", "protect", "defense", "guard"),
        "🔧" to listOf("wrench", "tool", "fix", "repair"),
        "🔩" to listOf("nut bolt", "screw", "tool", "hardware"),
        "⚙️" to listOf("gear", "settings", "cog", "mechanical"),
        "🪜" to listOf("ladder", "climb", "step", "reach"),
        "🧲" to listOf("magnet", "attract", "stick", "metal"),
        "🪛" to listOf("screwdriver", "tool", "fix", "screw"),
        "🔬" to listOf("microscope", "science", "lab", "research"),
        "🔭" to listOf("telescope", "space", "star", "astronomy"),
        "📡" to listOf("satellite antenna", "satellite", "signal", "communication"),
        "💉" to listOf("syringe", "vaccine", "injection", "medical"),
        "🩸" to listOf("drop blood", "blood", "medical", "donate"),
        "💊" to listOf("pill", "medicine", "drug", "health"),
        "🩹" to listOf("bandage", "wound", "heal", "medical"),
        "🩺" to listOf("stethoscope", "doctor", "medical", "health"),
        "🚪" to listOf("door", "entrance", "exit", "open"),
        "🛏️" to listOf("bed", "sleep", "rest", "bedroom"),
        "🛋️" to listOf("couch lamp", "sofa", "relax", "couch"),
        "🪑" to listOf("chair", "seat", "furniture", "sit"),
        "🚽" to listOf("toilet", "bathroom", "wc"),
        "🪠" to listOf("plunger", "drain", "unclog", "bathroom"),
        "🚿" to listOf("shower", "bath", "clean", "water"),
        "🛁" to listOf("bathtub", "bath", "relax"),
        "🪤" to listOf("mouse trap", "trap", "catch"),
        "🧴" to listOf("lotion bottle", "lotion", "cream", "skin"),
        "🧷" to listOf("safety pin", "pin", "fix", "sew"),
        "🧹" to listOf("broom", "sweep", "clean"),
        "🧺" to listOf("basket", "laundry", "wicker"),
        "🧻" to listOf("roll of paper", "toilet paper", "paper"),
        "🪣" to listOf("bucket", "water", "pail"),
        "🧼" to listOf("soap", "clean", "wash", "hygiene"),
        "🪥" to listOf("toothbrush", "teeth", "dental", "brush"),
        "🧽" to listOf("sponge", "clean", "scrub"),
        "🪒" to listOf("razor", "shave", "blade"),
        "🧻" to listOf("toilet paper", "paper", "roll"),
        "🪞" to listOf("mirror", "reflect", "vanity"),
        "🪟" to listOf("window", "glass", "view"),
        "🧸" to listOf("teddy bear", "bear", "toy", "cute", "plush"),
        "🪆" to listOf("nesting dolls", "russian doll", "matryoshka"),
        "🪅" to listOf("pinata", "party", "mexico", "candy"),
        "🎀" to listOf("ribbon", "bow", "pink", "gift"),
        "🎁" to listOf("gift", "present", "surprise", "wrap"),
        "📦" to listOf("package", "box", "delivery", "parcel"),
        "📬" to listOf("open mailbox raised flag", "mail", "letter", "post"),
        "📮" to listOf("postbox", "mail", "letter", "post"),
        "📭" to listOf("mailbox", "mail", "empty"),
        "📜" to listOf("scroll", "document", "ancient", "parchment"),
        "📄" to listOf("page document", "document", "paper", "file"),
        "📑" to listOf("bookmark tabs", "document", "pages"),
        "🗒️" to listOf("spiral notepad", "notes", "memo"),
        "🗓️" to listOf("spiral calendar", "calendar", "date", "schedule"),
        "📆" to listOf("tear off calendar", "calendar", "date"),
        "📅" to listOf("calendar", "date", "schedule"),
        "📇" to listOf("card index", "contacts", "index"),
        "📒" to listOf("ledger", "book", "notes"),
        "📓" to listOf("notebook", "notes", "write"),
        "📔" to listOf("notebook decorative cover", "notebook", "fancy"),
        "📕" to listOf("closed book", "book", "read"),
        "📗" to listOf("green book", "book", "read"),
        "📘" to listOf("blue book", "book", "read"),
        "📙" to listOf("orange book", "book", "read"),
        "📚" to listOf("books", "library", "study", "read", "education"),
        "🔖" to listOf("bookmark", "save", "read", "page"),
        "🏷️" to listOf("label", "tag", "price", "name"),
        "💼" to listOf("briefcase", "work", "business", "office"),
        "📁" to listOf("file folder", "folder", "organize"),
        "📂" to listOf("open file folder", "folder", "open"),
        "🗂️" to listOf("card index dividers", "organize", "divider"),
        "🗃️" to listOf("card file box", "box", "organize"),
        "🗄️" to listOf("file cabinet", "files", "office"),
        "📰" to listOf("newspaper", "news", "read", "print"),
        "🗞️" to listOf("rolled up newspaper", "newspaper", "news"),
        "📝" to listOf("memo", "note", "write", "pencil"),
        "✏️" to listOf("pencil", "write", "edit", "draw"),
        "✒️" to listOf("black nib", "pen", "write"),
        "🖊️" to listOf("pen", "write", "sign"),
        "🖋️" to listOf("fountain pen", "pen", "write", "ink"),
        "🖌️" to listOf("paintbrush", "paint", "art", "brush"),
        "🖍️" to listOf("crayon", "color", "draw", "art"),
        "🔍" to listOf("left magnifying glass", "search", "zoom", "find"),
        "🔎" to listOf("right magnifying glass", "search", "zoom"),
        "📞" to listOf("telephone receiver", "phone", "call", "talk"),
        "☎️" to listOf("telephone", "phone", "call", "old"),
        "📟" to listOf("pager", "beeper", "retro"),
        "📠" to listOf("fax machine", "fax", "office"),
        "📱" to listOf("mobile phone", "smartphone", "cell", "iphone"),
        "📲" to listOf("mobile phone arrow", "phone", "notification"),
        "💻" to listOf("laptop computer", "laptop", "computer", "work"),
        "🖥️" to listOf("desktop computer", "computer", "monitor", "pc"),
        "🖨️" to listOf("printer", "print", "office"),
        "⌨️" to listOf("keyboard", "type", "computer"),
        "🖱️" to listOf("computer mouse", "mouse", "click"),
        "🖲️" to listOf("trackball", "computer", "pointer"),
        "💾" to listOf("floppy disk", "save", "storage", "retro"),
        "💿" to listOf("optical disk", "cd", "dvd", "disc"),
        "📀" to listOf("dvd", "disc", "movie", "data"),
        "🧮" to listOf("abacus", "calculate", "math", "count"),
        "📷" to listOf("camera", "photo", "picture", "snap"),
        "📸" to listOf("camera flash", "photo", "selfie", "snap"),
        "📹" to listOf("video camera", "video", "record"),
        "🎥" to listOf("movie camera", "film", "cinema"),
        "📽️" to listOf("film projector", "cinema", "movie"),
        "🎞️" to listOf("film frames", "movie", "film"),
        "📞" to listOf("telephone", "phone", "call"),
        "☎️" to listOf("telephone", "call", "old phone"),
        "📟" to listOf("pager", "beeper"),
        "📠" to listOf("fax", "office"),
        "📺" to listOf("television", "tv", "watch"),
        "📻" to listOf("radio", "music", "broadcast"),
        "🎙️" to listOf("studio microphone", "record", "podcast"),
        "🎚️" to listOf("level slider", "audio"),
        "🎛️" to listOf("control knobs", "audio", "mixer"),
        "🧭" to listOf("compass", "direction", "navigate"),
        "⏱️" to listOf("stopwatch", "timer", "time", "speed"),
        "⏲️" to listOf("timer clock", "timer", "countdown"),
        "⏰" to listOf("alarm clock", "alarm", "wake up", "morning"),
        "🕰️" to listOf("mantelpiece clock", "clock", "vintage", "time"),
        "⌚" to listOf("watch", "time", "wrist", "smart watch"),
        "📡" to listOf("satellite antenna", "satellite", "signal"),
        "🔋" to listOf("battery", "power", "energy", "charge"),
        "🔌" to listOf("electric plug", "power", "charge", "plug"),
        "💡" to listOf("light bulb", "idea", "bright", "lit"),
        "🔦" to listOf("flashlight", "light", "torch"),
        "🕯️" to listOf("candle", "light", "romantic"),
        "🧱" to listOf("brick", "wall", "build"),
        "🪛" to listOf("screwdriver", "tool", "fix"),
        "🧰" to listOf("toolbox", "tools", "fix", "repair"),
        "⚗️" to listOf("alembic", "science", "experiment", "lab"),
        "🔭" to listOf("telescope", "space", "stars"),
        "🔬" to listOf("microscope", "science", "biology"),
        "🩺" to listOf("stethoscope", "doctor", "health"),
        "💉" to listOf("syringe", "needle", "injection", "vaccine"),
        "🩸" to listOf("blood drop", "blood", "medical"),
        "💊" to listOf("pill", "medicine", "drug"),
        "🩹" to listOf("adhesive bandage", "bandage", "hurt"),
        "🚑" to listOf("ambulance", "emergency", "hospital"),

        // Symbols
        "❤️" to listOf("red heart", "love", "heart", "romance"),
        "🧡" to listOf("orange heart", "love", "heart", "orange"),
        "💛" to listOf("yellow heart", "love", "heart", "yellow"),
        "💚" to listOf("green heart", "love", "heart", "nature"),
        "💙" to listOf("blue heart", "love", "heart", "trust"),
        "💜" to listOf("purple heart", "love", "heart", "military"),
        "🖤" to listOf("black heart", "dark", "heart", "evil"),
        "🤍" to listOf("white heart", "pure", "heart", "love"),
        "🤎" to listOf("brown heart", "heart", "love", "brown"),
        "💔" to listOf("broken heart", "heartbreak", "sad", "relationship"),
        "❣️" to listOf("heart exclamation", "love", "important"),
        "💕" to listOf("two hearts", "love", "cute", "romance"),
        "💞" to listOf("revolving hearts", "love", "romance"),
        "💓" to listOf("beating heart", "love", "alive"),
        "💗" to listOf("growing heart", "love", "care"),
        "💖" to listOf("sparkling heart", "love", "glitter"),
        "💘" to listOf("heart arrow", "cupid", "love", "valentine"),
        "💝" to listOf("heart ribbon", "gift", "love"),
        "💟" to listOf("heart decoration", "love", "purple"),
        "☮️" to listOf("peace symbol", "peace", "hippie"),
        "✝️" to listOf("latin cross", "christian", "religion"),
        "☪️" to listOf("star crescent", "islam", "religion"),
        "🕉️" to listOf("om", "hindu", "religion", "meditation"),
        "✡️" to listOf("star of david", "jewish", "religion"),
        "⚛️" to listOf("atom symbol", "science", "physics"),
        "☯️" to listOf("yin yang", "balance", "taoism"),
        "✴️" to listOf("eight pointed star", "star", "sparkle"),
        "🆚" to listOf("vs button", "versus", "compare"),
        "🆕" to listOf("new button", "new", "fresh"),
        "🆓" to listOf("free button", "free", "gratis"),
        "🆙" to listOf("up button", "up", "upgrade"),
        "🆒" to listOf("cool button", "cool", "awesome"),
        "🆗" to listOf("ok button", "okay", "approved"),
        "🆙" to listOf("up", "upgrade"),
        "🔴" to listOf("red circle", "red", "dot", "warning"),
        "🟠" to listOf("orange circle", "orange", "dot"),
        "🟡" to listOf("yellow circle", "yellow", "dot"),
        "🟢" to listOf("green circle", "green", "dot", "go"),
        "🔵" to listOf("blue circle", "blue", "dot"),
        "🟣" to listOf("purple circle", "purple", "dot"),
        "⚫" to listOf("black circle", "black", "dark"),
        "⚪" to listOf("white circle", "white", "empty"),
        "🟤" to listOf("brown circle", "brown", "dot"),
        "🔶" to listOf("large orange diamond", "diamond", "orange"),
        "🔷" to listOf("large blue diamond", "diamond", "blue"),
        "🔸" to listOf("small orange diamond", "diamond", "orange", "small"),
        "🔹" to listOf("small blue diamond", "diamond", "blue", "small"),
        "🔺" to listOf("red triangle up", "triangle", "red", "up"),
        "🔻" to listOf("red triangle down", "triangle", "red", "down"),
        "💠" to listOf("diamond blue circle", "diamond", "pattern"),
        "🔘" to listOf("radio button", "circle", "select"),
        "🔲" to listOf("black square button", "square", "black"),
        "🔳" to listOf("white square button", "square", "white"),
        "⬛" to listOf("black large square", "black", "square"),
        "⬜" to listOf("white large square", "white", "square"),
        "◼️" to listOf("black medium square", "black", "square"),
        "◻️" to listOf("white medium square", "white", "square"),
        "▪️" to listOf("black small square", "black", "tiny"),
        "▫️" to listOf("white small square", "white", "tiny"),
        "🌐" to listOf("globe meridians", "web", "internet", "global", "world"),
        "🗺️" to listOf("world map", "map", "travel"),
        "🧿" to listOf("nazar amulet", "evil eye", "protection"),
        "⭕" to listOf("hollow red circle", "circle", "red"),
        "❌" to listOf("cross mark", "wrong", "error", "no", "x"),
        "❎" to listOf("cross mark button", "wrong", "no"),
        "✅" to listOf("check mark button", "check", "correct", "yes", "done"),
        "☑️" to listOf("check box check", "checked", "done"),
        "✔️" to listOf("check mark", "correct", "yes", "done", "tick"),
        "➕" to listOf("plus sign", "add", "more", "positive"),
        "➖" to listOf("minus sign", "subtract", "less"),
        "➗" to listOf("division sign", "divide", "math"),
        "✖️" to listOf("multiply", "times", "math", "x"),
        "♾️" to listOf("infinity", "forever", "endless", "loop"),
        "💲" to listOf("dollar sign", "money", "usd"),
        "💱" to listOf("currency exchange", "money", "forex"),
        "™️" to listOf("trademark", "brand", "registered"),
        "©️" to listOf("copyright", "rights", "reserved"),
        "®️" to listOf("registered", "trademark", "brand"),
        "🔱" to listOf("trident emblem", "poseidon", "water"),
        "⚜️" to listOf("fleur de lis", "france", "symbol"),
        "🔰" to listOf("japanese symbol beginner", "japan", "beginner"),
        "♻️" to listOf("recycling symbol", "recycle", "green", "eco"),
        "⚠️" to listOf("warning", "caution", "danger", "alert"),
        "⛔" to listOf("no entry", "stop", "forbidden", "banned"),
        "🚫" to listOf("prohibited", "no", "forbidden", "ban"),
        "🔞" to listOf("no one under 18", "adult", "18 plus", "restricted"),
        "🔇" to listOf("muted speaker", "mute", "silent", "no sound"),
        "🔈" to listOf("speaker low volume", "sound", "audio"),
        "🔉" to listOf("speaker medium volume", "sound", "audio"),
        "🔊" to listOf("speaker high volume", "loud", "sound", "audio"),
        "🔕" to listOf("bell with slash", "no notification", "silent", "mute"),
        "🔔" to listOf("bell", "notification", "alert", "ring"),
        "📢" to listOf("loudspeaker", "announce", "megaphone"),
        "📣" to listOf("megaphone", "cheer", "loud"),
        "🔀" to listOf("shuffle tracks button", "shuffle", "random"),
        "🔁" to listOf("repeat button", "loop", "repeat", "cycle"),
        "🔂" to listOf("repeat single button", "repeat one", "loop"),
        "▶️" to listOf("play button", "play", "start", "video"),
        "⏩" to listOf("fast forward button", "fast forward", "skip"),
        "⏭️" to listOf("next track button", "next", "skip"),
        "⏮️" to listOf("previous track button", "previous", "back"),
        "◀️" to listOf("reverse button", "back", "rewind"),
        "⏪" to listOf("fast reverse button", "rewind", "back"),
        "⏏️" to listOf("eject button", "eject", "disc"),
        "⏺️" to listOf("record button", "record", "dot"),
        "⏹️" to listOf("stop button", "stop"),
        "⏸️" to listOf("pause button", "pause"),
        "🔼" to listOf("upwards button", "up", "increase"),
        "🔽" to listOf("downwards button", "down", "decrease"),
        "⏫" to listOf("fast up button", "skip up"),
        "⏬" to listOf("fast down button", "skip down"),
        "⬆️" to listOf("up arrow", "up", "north"),
        "↗️" to listOf("up right arrow", "northeast"),
        "➡️" to listOf("right arrow", "right", "east"),
        "↘️" to listOf("down right arrow", "southeast"),
        "⬇️" to listOf("down arrow", "down", "south"),
        "↙️" to listOf("down left arrow", "southwest"),
        "⬅️" to listOf("left arrow", "left", "west", "back"),
        "↖️" to listOf("up left arrow", "northwest"),
        "↕️" to listOf("up down arrow", "vertical"),
        "↔️" to listOf("left right arrow", "horizontal"),
        "🔃" to listOf("clockwise arrows button", "refresh", "reload"),
        "🔄" to listOf("counterclockwise arrows button", "reload", "refresh"),
        "🔙" to listOf("back arrow", "back", "return"),
        "🔚" to listOf("end arrow", "end"),
        "🔛" to listOf("on arrow", "on"),
        "🔜" to listOf("soon arrow", "soon", "coming"),
        "🔝" to listOf("top arrow", "top", "best"),
        "🆕" to listOf("new", "fresh"),
        "🆙" to listOf("up", "improve"),
        "🆒" to listOf("cool"),
        "🆗" to listOf("ok", "okay"),
        "🆕" to listOf("new"),

        // Weather & Nature
        "🌞" to listOf("sun face", "sun", "sunny", "summer", "bright"),
        "🌝" to listOf("full moon face", "moon", "night"),
        "🌛" to listOf("first quarter moon face", "moon"),
        "🌜" to listOf("last quarter moon face", "moon"),
        "🌚" to listOf("new moon face", "dark", "moon"),
        "🌕" to listOf("full moon", "moon", "night", "white"),
        "🌖" to listOf("waning gibbous moon", "moon"),
        "🌗" to listOf("last quarter moon", "moon"),
        "🌘" to listOf("waning crescent moon", "moon"),
        "🌑" to listOf("new moon", "moon", "dark"),
        "🌒" to listOf("waxing crescent moon", "moon"),
        "🌓" to listOf("first quarter moon", "moon"),
        "🌔" to listOf("waxing gibbous moon", "moon"),
        "🌙" to listOf("crescent moon", "moon", "night", "sleep"),
        "🌟" to listOf("glowing star", "star", "shine", "bright"),
        "⭐" to listOf("star", "favorite", "rate", "shine"),
        "🌠" to listOf("shooting star", "wish", "star"),
        "🌤️" to listOf("sun small cloud", "partly cloudy", "weather"),
        "⛅" to listOf("partly cloudy", "cloud", "sun", "weather"),
        "🌥️" to listOf("cloud sun", "overcast", "weather"),
        "☁️" to listOf("cloud", "overcast", "sky", "weather"),
        "🌦️" to listOf("sun rain", "rain shower", "weather"),
        "🌧️" to listOf("rain cloud", "rain", "wet", "weather"),
        "⛈️" to listOf("thunderstorm", "storm", "lightning", "rain"),
        "🌩️" to listOf("lightning cloud", "lightning", "storm"),
        "🌨️" to listOf("snow cloud", "snow", "winter", "cold"),
        "❄️" to listOf("snowflake", "snow", "cold", "winter", "ice"),
        "☃️" to listOf("snowman", "snow", "winter", "cold"),
        "⛄" to listOf("snowman no snow", "snowman", "winter"),
        "🌬️" to listOf("wind face", "wind", "blow", "air"),
        "💨" to listOf("dashing away", "wind", "fast", "blow"),
        "💧" to listOf("droplet", "water", "drop", "rain"),
        "💦" to listOf("sweat droplets", "water", "splash", "wet"),
        "🌊" to listOf("wave", "ocean", "sea", "surf", "water"),
        "🌈" to listOf("rainbow", "colorful", "hope", "pride"),
        "🌫️" to listOf("fog", "mist", "haze", "cloudy"),
        "🌀" to listOf("cyclone", "hurricane", "tornado", "spiral"),
        "🌪️" to listOf("tornado", "twister", "storm", "wind"),
        "🌡️" to listOf("thermometer", "temperature", "hot", "cold"),
        "🔥" to listOf("fire", "flame", "hot", "lit", "trending"),
        "💥" to listOf("collision", "explosion", "boom", "crash"),
        "❓" to listOf("question mark", "question", "ask", "help"),
        "❗" to listOf("exclamation mark", "important", "alert"),
        "💬" to listOf("speech bubble", "chat", "talk", "message"),
        "💭" to listOf("thought balloon", "thinking", "thought"),
        "💫" to listOf("dizzy star", "sparkle", "daze"),
        "⚡" to listOf("lightning bolt", "electric", "power", "fast"),
        "🌱" to listOf("seedling", "plant", "grow", "nature", "new"),
        "🌿" to listOf("herb", "plant", "green", "nature"),
        "🍀" to listOf("four leaf clover", "lucky", "luck", "green"),
        "🌸" to listOf("cherry blossom", "flower", "pink", "spring", "japan"),
        "🌺" to listOf("hibiscus", "flower", "tropical", "red"),
        "🌻" to listOf("sunflower", "flower", "yellow", "summer"),
        "🌹" to listOf("rose", "flower", "red", "love", "romance"),
        "🥀" to listOf("wilted flower", "dead flower", "sad"),
        "🌷" to listOf("tulip", "flower", "pink", "spring"),
        "🌵" to listOf("cactus", "desert", "spiky", "plant"),
        "🎋" to listOf("tanabata tree", "bamboo", "japan", "wish"),
        "🎍" to listOf("pine decoration", "pine", "japan", "new year"),
        "🍃" to listOf("leaf fluttering wind", "leaf", "nature", "green"),
        "🍂" to listOf("fallen leaf", "autumn", "fall", "brown"),
        "🍁" to listOf("maple leaf", "autumn", "fall", "canada", "red"),
        "🌾" to listOf("sheaf rice", "wheat", "grain", "harvest"),
        "☘️" to listOf("shamrock", "ireland", "lucky", "green"),
        "⛱️" to listOf("umbrella beach", "beach", "parasol", "vacation"),
        "🌍" to listOf("globe europe africa", "world", "earth", "global"),
        "🌎" to listOf("globe americas", "world", "earth", "global"),
        "🌏" to listOf("globe asia australia", "world", "earth", "global"),
        "🌐" to listOf("globe meridians", "internet", "web", "network")
    )

    /**
     * Returns emojis whose keywords contain a word starting with [query] (case-insensitive).
     * Empty query returns all emojis in insertion order.
     */
    fun searchEmojis(query: String): List<String> {
        val trimmed = query.trim()
        if (trimmed.isEmpty()) return table.keys.toList()
        val lower = trimmed.lowercase()
        return table.entries
            .filter { (_, keywords) -> keywords.any { it.startsWith(lower) } }
            .map { it.key }
    }
}
